### ISSUE TITLE
SetCurrentModes error

### ISSUE THREAD

**Issue by benat974** [maltegrosse/go-modemmanager#2]
Hey, first thanks for your modem manager package. it's a great implementation of modem manage dbus api.

I tried to set the current mode of my modem via the method SetCurrentModes() and I get following error : 
_Type of message, “(au)”, does not match expected type “((uu))”_

source code  : 

```
defaultModemMode := modemmanager.Mode{
	AllowedModes:  []modemmanager.MMModemMode{modemmanager.MmModemMode3g, modemmanager.MmModemMode4g},
	PreferredMode: modemmanager.MmModemMode4g,
}
mmgr, err := modemmanager.NewModemManager()
if err != nil {
  return err
}
modems, err := mmgr.GetModems()
if err != nil {
  return err
}
for _, modem := range modems {
  err := modem.SetCurrentModes(defaultModemMode)
  if err != nil {
    fmt.Println(err.Error())
  }
}
```

I thinks it's a problem with type of parameter pass to dbus. Have you any idea to correct it ?

Thanks for all
Ben

**Comment by maltegrosse** [comment]
Hi Ben,

thank you for your feedback. 
As you can see  [here](https://github.com/maltegrosse/go-modemmanager/blob/master/Modem.go#L447) this function is one of these i havent found the time to test it.
the dbus api expects a tuple of two uint (uu), but I pass a slice of uints (au) - thats the bug.
I created a pair struct to somehow represent the dbus tuples, and i always read them from dbus ([see](https://github.com/maltegrosse/go-modemmanager/blob/master/utils.go#L236) )
but I never tried to provide the dbus api a tuple. (from dbus tuple to golang its a simple slice with length 2)

I could not find anything about handling tuples with godbus lib.

The easiest way would be to try and error :-)

I currently dont have my hardware around, but your could try following:
change following method and create a pair struct out of the property mode struct
https://github.com/maltegrosse/go-modemmanager/blob/master/Modem.go#L446

```
func (m modem) SetCurrentModes(property Mode) error {
	// todo: untested
	var mode MMModemMode
	var p Pair
	p.SetLeft(mode.SliceToBitmask(property.AllowedModes))
	p.SetRight(mode.SliceToBitmask([]MMModemMode{property.PreferredMode}))
        
	return m.call(ModemSetCurrentModes, p)
}
```

if it works, a PR would be great!

BR Malte

**Comment by benat974** [comment]
Hi Thanks for your quickly feedback. 
I done more test and the message  _Type of message, “(au)”, does not match expected type “((uu))”_ is in fact a warning message. Modem manager apply correctly the command. In my case, the current mode of modem is correctly configured. My issue is not blocking.

Ben

**Comment by maltegrosse** [comment]
As I am happy whatever connection I can get in my country, I never tested it ;-) 
if mmcli -m 0 shows your correct modes - everything should be fine....
