### ISSUE TITLE
Release for current codebase?

### ISSUE THREAD

**Issue by 418Coffee** [maltegrosse/go-modemmanager#6]
Hi, 

First, thank you for writing these bindings, they saved me a lot of time.
I noticed that the current released version (v0.1.0) is no longer up to date, and misses some patches like removing debug outputs. 
Would it be possible to release a patch version e.g. v0.1.1 or a minor version v0.2.0 for the current codebase?

Thank you.

**Comment by maltegrosse** [comment]
Hi, 
thanks for you feedback. I added a new tag, is that fine?
https://github.com/maltegrosse/go-modemmanager/releases/tag/v0.1.1

**Comment by 418Coffee** [comment]
Yes perfect, thank you very much!
